[profile.default]
src = "src/v2"
out = "out/v2"
libs = ["lib", "dependencies"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 9999999
via_ir = true
remappings = [
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.3.0/",
]

[profile.v1]
src = "src/v1"
out = "out/v1"
libs = ["lib", "dependencies"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 9999999
remappings = [
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.3.0/",
]

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.3.0"
"@openzeppelin-contracts-upgradeable" = "5.3.0"
diamond-3-hardhat = { version = "1.0.0", git = "https://github.com/mudgen/diamond-3-hardhat.git", rev = "08d415c7e1a27c811c34875d9263a90bc719cee3" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
